[2023-03-28T00:18:57.290+0200] {processor.py:153} INFO - Started process (PID=23683) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:18:57.290+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:18:57.292+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:18:57.291+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:18:57.480+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:18:57.463+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 19, in <module>
    from load import INSERT_INTO_TABLE
  File "/home/humbulani/airflow/load.py", line 14, in <module>
    from new import df_to_tuple
  File "/home/humbulani/airflow/new.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-28T00:18:57.481+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:18:57.588+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.300 seconds
[2023-03-28T00:19:44.482+0200] {processor.py:153} INFO - Started process (PID=23728) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:19:44.494+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:19:44.495+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:19:44.495+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:19:44.537+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:19:44.536+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 19, in <module>
    from load import INSERT_INTO_TABLE
  File "/home/humbulani/airflow/load.py", line 14, in <module>
    from new import df_to_tuple
  File "/home/humbulani/airflow/new.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-28T00:19:44.537+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:19:44.618+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.139 seconds
[2023-03-28T00:20:37.224+0200] {processor.py:153} INFO - Started process (PID=23780) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:20:37.234+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:20:37.235+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:20:37.235+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:20:37.276+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:20:37.275+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 19, in <module>
    from load import INSERT_INTO_TABLE
  File "/home/humbulani/airflow/load.py", line 14, in <module>
    from new import df_to_tuple
  File "/home/humbulani/airflow/new.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-28T00:20:37.277+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:20:37.350+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.128 seconds
[2023-03-28T00:21:41.450+0200] {processor.py:153} INFO - Started process (PID=23850) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:21:41.520+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:21:41.520+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:21:41.520+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:21:41.566+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:21:41.565+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 19, in <module>
    from load import INSERT_INTO_TABLE
  File "/home/humbulani/airflow/load.py", line 14, in <module>
    from new import df_to_tuple
  File "/home/humbulani/airflow/new.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-03-28T00:21:41.566+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:21:41.649+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.202 seconds
[2023-03-28T00:42:58.882+0200] {processor.py:153} INFO - Started process (PID=25490) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:42:58.897+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:42:58.898+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:42:58.898+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:42:58.993+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:42:58.993+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:42:59.301+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:42:59.300+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:42:59.301+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:42:59.368+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.489 seconds
[2023-03-28T00:43:29.543+0200] {processor.py:153} INFO - Started process (PID=25554) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:43:29.544+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:43:29.544+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:43:29.544+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:43:29.608+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:43:29.608+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:43:29.844+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:43:29.843+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:43:29.844+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:43:29.945+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.404 seconds
[2023-03-28T00:44:00.070+0200] {processor.py:153} INFO - Started process (PID=25566) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:00.082+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:44:00.083+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:00.083+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:00.160+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:00.159+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:44:00.392+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:00.391+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:44:00.392+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:00.486+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.418 seconds
[2023-03-28T00:44:30.673+0200] {processor.py:153} INFO - Started process (PID=25579) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:30.685+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:44:30.686+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:30.686+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:30.751+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:30.750+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:44:30.973+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:44:30.973+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:44:30.974+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:44:31.042+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.373 seconds
[2023-03-28T00:45:01.165+0200] {processor.py:153} INFO - Started process (PID=25617) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:01.165+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:45:01.166+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:01.166+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:01.226+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:01.226+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:45:01.471+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:01.470+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:45:01.472+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:01.586+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.424 seconds
[2023-03-28T00:45:31.765+0200] {processor.py:153} INFO - Started process (PID=25667) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:31.780+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:45:31.781+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:31.781+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:31.851+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:31.851+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:45:32.067+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:45:32.066+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:45:32.067+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:45:32.135+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.374 seconds
[2023-03-28T00:46:02.325+0200] {processor.py:153} INFO - Started process (PID=25677) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:02.331+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:46:02.331+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:02.331+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:02.390+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:02.390+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:46:02.607+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:02.606+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:46:02.607+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:02.674+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.353 seconds
[2023-03-28T00:46:32.860+0200] {processor.py:153} INFO - Started process (PID=25689) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:32.861+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:46:32.862+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:32.861+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:32.923+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:32.923+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:46:33.152+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:46:33.151+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:46:33.152+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:46:33.242+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.385 seconds
[2023-03-28T00:47:03.386+0200] {processor.py:153} INFO - Started process (PID=25701) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:03.397+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:47:03.398+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:03.398+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:03.467+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:03.467+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:47:03.716+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:03.715+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:47:03.716+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:03.784+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.401 seconds
[2023-03-28T00:47:33.956+0200] {processor.py:153} INFO - Started process (PID=25710) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:33.966+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:47:33.967+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:33.967+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:34.037+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:34.037+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:47:34.273+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:47:34.272+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:47:34.273+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:47:34.353+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.400 seconds
[2023-03-28T00:48:04.544+0200] {processor.py:153} INFO - Started process (PID=25721) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:04.544+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:48:04.545+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:04.545+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:04.604+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:04.604+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:48:04.832+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:04.831+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:48:04.832+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:04.972+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.431 seconds
[2023-03-28T00:48:35.111+0200] {processor.py:153} INFO - Started process (PID=25731) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:35.123+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:48:35.124+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:35.124+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:35.186+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:35.185+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:48:35.409+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:48:35.408+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:48:35.410+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:48:35.525+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.416 seconds
[2023-03-28T00:49:05.693+0200] {processor.py:153} INFO - Started process (PID=25742) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:05.693+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:49:05.694+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:05.694+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:05.755+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:05.755+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:49:05.969+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:05.969+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:49:05.970+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:06.034+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.345 seconds
[2023-03-28T00:49:36.155+0200] {processor.py:153} INFO - Started process (PID=25751) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:36.159+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:49:36.160+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:36.160+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:36.221+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:36.221+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:49:36.436+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:49:36.435+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:49:36.436+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:49:36.517+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.365 seconds
[2023-03-28T00:50:06.661+0200] {processor.py:153} INFO - Started process (PID=25768) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:06.662+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:50:06.662+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:06.662+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:06.723+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:06.723+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:50:06.952+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:06.951+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:50:06.952+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:07.028+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.369 seconds
[2023-03-28T00:50:37.163+0200] {processor.py:153} INFO - Started process (PID=25782) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:37.179+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:50:37.180+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:37.180+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:37.248+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:37.248+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:50:37.507+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:50:37.507+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_dag_settings does not exist'
[2023-03-28T00:50:37.508+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:50:37.589+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.428 seconds
[2023-03-28T00:51:07.731+0200] {processor.py:153} INFO - Started process (PID=25796) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:07.732+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:51:07.732+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:07.732+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:07.799+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:07.799+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:51:08.056+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:08.043+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 144, in get
    obj = json.loads(var_val)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 78 (char 77)
[2023-03-28T00:51:08.057+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:08.143+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.415 seconds
[2023-03-28T00:51:38.297+0200] {processor.py:153} INFO - Started process (PID=25806) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:38.298+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:51:38.299+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:38.298+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:38.371+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:38.370+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:51:38.617+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:51:38.616+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 144, in get
    obj = json.loads(var_val)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 78 (char 77)
[2023-03-28T00:51:38.617+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:51:38.721+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.427 seconds
[2023-03-28T00:52:08.884+0200] {processor.py:153} INFO - Started process (PID=25819) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:08.911+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:52:08.912+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:08.911+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:08.972+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:08.972+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:52:09.209+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:09.208+0200] {dagbag.py:341} ERROR - Failed to import: /home/humbulani/airflow/dags/new2_dag.py
Traceback (most recent call last):
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/humbulani/airflow/dags/new2_dag.py", line 49, in <module>
    task1 = PythonOperator(task_id="insert_data", python_callable=INSERT_INTO_TABLE, op_kwargs=Variable.get("mysql_dag_settings", deserialize_json=True))
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/site-packages/airflow/models/variable.py", line 144, in get
    obj = json.loads(var_val)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/humbulani/miniconda3/envs/apache-airflow/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 78 (char 77)
[2023-03-28T00:52:09.209+0200] {processor.py:755} WARNING - No viable dags retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:09.322+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.440 seconds
[2023-03-28T00:52:39.474+0200] {processor.py:153} INFO - Started process (PID=25832) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:39.475+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:52:39.475+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:39.475+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:39.536+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:39.536+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:52:39.768+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:52:40.036+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.036+0200] {manager.py:504} INFO - Created Permission View: can edit on DAG:mysql_dag
[2023-03-28T00:52:40.112+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.111+0200] {manager.py:504} INFO - Created Permission View: can delete on DAG:mysql_dag
[2023-03-28T00:52:40.212+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.211+0200] {manager.py:504} INFO - Created Permission View: can read on DAG:mysql_dag
[2023-03-28T00:52:40.212+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.212+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:52:40.222+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.222+0200] {dag.py:2714} INFO - Creating ORM DAG for mysql_dag
[2023-03-28T00:52:40.231+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:52:40.231+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:52:40.392+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.921 seconds
[2023-03-28T00:53:10.553+0200] {processor.py:153} INFO - Started process (PID=25844) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:10.553+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:53:10.554+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:10.554+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:10.616+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:10.616+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:53:10.856+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:10.871+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:10.871+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:53:10.893+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:10.892+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:53:11.021+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.471 seconds
[2023-03-28T00:53:41.168+0200] {processor.py:153} INFO - Started process (PID=25861) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:41.169+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:53:41.169+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:41.169+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:41.232+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:41.232+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:53:41.461+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:53:41.474+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:41.473+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:53:41.494+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:53:41.494+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:53:41.655+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.489 seconds
[2023-03-28T00:54:11.825+0200] {processor.py:153} INFO - Started process (PID=25874) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:11.826+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:54:11.826+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:11.826+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:11.894+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:11.893+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:54:12.132+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:12.146+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:12.146+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:54:12.168+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:12.167+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:54:12.320+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.498 seconds
[2023-03-28T00:54:42.444+0200] {processor.py:153} INFO - Started process (PID=25883) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:42.456+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:54:42.457+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:42.456+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:42.518+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:42.518+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:54:42.748+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:54:42.761+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:42.761+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:54:42.783+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:54:42.783+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:54:42.859+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.417 seconds
[2023-03-28T00:55:13.006+0200] {processor.py:153} INFO - Started process (PID=25910) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:13.006+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:55:13.007+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:13.007+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:13.071+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:13.071+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:55:13.364+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:13.386+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:13.386+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:55:13.424+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:13.424+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:55:13.590+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.587 seconds
[2023-03-28T00:55:43.740+0200] {processor.py:153} INFO - Started process (PID=25920) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:43.746+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:55:43.747+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:43.746+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:43.808+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:43.807+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:55:44.032+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:55:44.045+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:44.045+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:55:44.064+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:55:44.064+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:55:44.140+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.403 seconds
[2023-03-28T00:56:14.312+0200] {processor.py:153} INFO - Started process (PID=25933) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:14.313+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:56:14.313+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:14.313+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:14.376+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:14.375+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:56:14.602+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:14.616+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:14.616+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:56:14.636+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:14.636+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:56:14.714+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.404 seconds
[2023-03-28T00:56:44.878+0200] {processor.py:153} INFO - Started process (PID=25946) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:44.883+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:56:44.884+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:44.884+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:44.951+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:44.951+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:56:45.182+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:56:45.223+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:45.223+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:56:45.335+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:56:45.335+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:56:45.438+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.563 seconds
[2023-03-28T00:57:15.585+0200] {processor.py:153} INFO - Started process (PID=25968) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:15.586+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:57:15.586+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:15.586+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:15.663+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:15.662+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:57:15.916+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:15.930+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:15.930+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:57:15.953+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:15.953+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:57:16.258+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.675 seconds
[2023-03-28T00:57:46.390+0200] {processor.py:153} INFO - Started process (PID=25977) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:46.404+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:57:46.405+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:46.405+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:46.470+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:46.470+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:57:46.730+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:57:46.746+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:46.746+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:57:46.770+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:57:46.769+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:57:46.872+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.485 seconds
[2023-03-28T00:58:17.019+0200] {processor.py:153} INFO - Started process (PID=25989) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:17.019+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:58:17.020+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:17.020+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:17.080+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:17.080+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:58:17.302+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:17.316+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:17.316+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:58:17.337+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:17.337+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:58:17.527+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.511 seconds
[2023-03-28T00:58:47.721+0200] {processor.py:153} INFO - Started process (PID=26001) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:47.733+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:58:47.734+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:47.734+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:47.795+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:47.795+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:58:48.016+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:58:48.030+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:48.030+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:58:48.051+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:58:48.050+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:58:48.131+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.414 seconds
[2023-03-28T00:59:18.297+0200] {processor.py:153} INFO - Started process (PID=26012) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:18.298+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:59:18.298+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:18.298+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:18.360+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:18.360+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:59:18.589+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:18.602+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:18.601+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:59:18.621+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:18.620+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:59:18.697+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.404 seconds
[2023-03-28T00:59:48.871+0200] {processor.py:153} INFO - Started process (PID=26021) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:48.879+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T00:59:48.879+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:48.879+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:48.943+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:48.942+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T00:59:49.173+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T00:59:49.187+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:49.187+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T00:59:49.208+0200] {logging_mixin.py:137} INFO - [2023-03-28T00:59:49.208+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T00:59:49.311+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.442 seconds
[2023-03-28T01:00:19.469+0200] {processor.py:153} INFO - Started process (PID=26031) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:19.470+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T01:00:19.470+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:19.470+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:19.532+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:19.532+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T01:00:19.764+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:19.778+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:19.778+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T01:00:19.799+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:19.798+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T01:00:19.964+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.499 seconds
[2023-03-28T01:00:50.128+0200] {processor.py:153} INFO - Started process (PID=26043) to work on /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:50.134+0200] {processor.py:743} INFO - Processing file /home/humbulani/airflow/dags/new2_dag.py for tasks to queue
[2023-03-28T01:00:50.135+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:50.135+0200] {dagbag.py:532} INFO - Filling up the DagBag from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:50.200+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:50.200+0200] {utils.py:160} INFO - NumExpr defaulting to 4 threads.
[2023-03-28T01:00:50.428+0200] {processor.py:753} INFO - DAG(s) dict_keys(['mysql_dag']) retrieved from /home/humbulani/airflow/dags/new2_dag.py
[2023-03-28T01:00:50.442+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:50.442+0200] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T01:00:50.553+0200] {logging_mixin.py:137} INFO - [2023-03-28T01:00:50.553+0200] {dag.py:3440} INFO - Setting next_dagrun for mysql_dag to None, run_after=None
[2023-03-28T01:00:50.676+0200] {processor.py:175} INFO - Processing /home/humbulani/airflow/dags/new2_dag.py took 0.550 seconds
